### ISSUE TITLE
Conversation Topic

### ISSUE THREAD

**Issue by itsbenter** [purrplingcat/QuestFramework#14]
1. What is the goal?
Making other NPCs say different dialogue when the player started and or completed a quest.
2. What is the benefit?
More immersion as quest can now be "acknowledged" by other NPCs
3. Example:
Quest where Lewis asked the player to submit items for a festival. With this feature, NPCs beside Lewis and Lewis himself could make commentary related to the quest. For example, Leah could say "I can't wait to see your pumpkins at the upcoming festival."

**Description:**
Add option to [addConversationTopic ](https://stardewvalleywiki.com/Modding:Dialogue#Conversation_topics)at the start or at the completion of a quest.

When a conversation topic is active, the NPCs will use different dialogue based on the key of the active conversation topic. Adding the dialogue requires CP.

This feature could be implemented by adding more lines to the format for quests.json like:
"AddConversationTopicWhenAccept": "key duration"
"AddConversationTopicWhenCompleted": "key duration"
Another possibility is to make AddConversationTopic as an "action". I haven't used that QF feature, so I'm not sure.
   
It is mentioned in the wiki, Conversation Topic could be added through code by adding the conversation topic to `Game1.player.activeDialogueEvents`. But, I'm not sure what it means exactly...

*If removing the conversation topic is possible, it might be nice to have the option to remove the conversation topic. This will be useful to remove the conversation topic that was meant to be shown when the quest itself is active.
"RemoveConversationTopicWhenCompleted": "key"

**How it will work:**
Modder specifies the key for conversation topic with QF. Then add the dialogue using CP. In the mentioned example with Lewis' quest, the modder will add the conversation key in the quests:
"AddConversationTopicWhenAccept": "LewisFestival 3" // this mean the conversation topic is "LewisFestival" and it would be active for three days.
Then with CP, modder target Leah's dialogue and add the line:
"LewisFestival": "I can't wait to see your pumpkins at the upcoming festival."

**Comment by purrplingcat** [comment]
I don't plan implement it in soon verisons of QF. It's far future feature. If you want to have it in QF ASAP, you can implement it and send me PR. I will love you.

**Comment by itsbenter** [comment]
Haha seems like beyond what I can do atm.
