### ISSUE TITLE
Kent offering a quest in Year 1 and "System.ArgumentNullException: Value cannot be null."

### ISSUE THREAD

**Issue by LenneDalben** [purrplingcat/QuestFramework#18]
Hi purrplingcat! A user of Townies Need Food reported that Kent requested risotto in year 1 in the bulletin board, even though the user hadn't yet met Kent. In my testing, I hadn't seen a quest offered by an NPC I hadn't met yet, so I think this may be an issue within Quest Framework. The user provided their log ( https://smapi.io/log/f61cd560435249d6a576ca829393a336 ) and there's a Trace message for Quest Framework for "System.ArgumentNullException: Value cannot be null."

**Comment by purrplingcat** [comment]
Outsourcing for community. Anyone who who SMAPI coding can try fix it.

**Comment by purrplingcat** [comment]
By the fast log check: It's a fail in checking game patches, nothing critical and it's not connected with quest offers, so this can't cause Kent quest offer in first year. Please check your Kent offer if he has right condition setup. Have your offer condition for don't offer it in year 1?

**Comment by LenneDalben** [comment]
No, because in my testing, if I hadn't met the NPC, they didn't offer quests on the bulletin board. I thought this was a vanilla feature and I didn't need to set up anything further. Is that not a vanilla feature, that if you haven't met the NPC, they can't post a quest on the bulletin board?

**Comment by purrplingcat** [comment]
Quest is not offered by NPC to a borad, quest is offered on the board by quest offer service in QF and that service offers quests based on the conditions. Check your conditions.

**Comment by LenneDalben** [comment]
Ok, thanks purrplingcat! I will add a condition for EventSeen to include the Kent intro event. Feel free to close this :)

**Comment by LenneDalben** [comment]
As you'd mentioned via Discord, EventSeen does take multiple entries, and the delimiter / separator is a space. Thank you so much, PurrplingCat!
