### ISSUE TITLE
Quest Objective Got Switched

### ISSUE THREAD

**Issue by Craylicia** [purrplingcat/QuestFramework#23]
Hi! 

I'm currently using the mod "Townies Need Food" and one of my quest objectives got switched.

Says here that Sam needs me to harvest 229 corn, but I asked around in the SDV Discord Server and I was told that in the original quest, Sam wants me to deliver him a tortilla, not to harvest 229 corn. 

My SMAPI log: https://smapi.io/log/b9a1cbedb0da4a088eeeffd22ce6200a

I hope it'll be fixed. 

Thank you!
![1](https://user-images.githubusercontent.com/77601325/104872191-20769a00-5988-11eb-909b-6c28d7e0e1b0.PNG)

**Comment by purrplingcat** [comment]
It's like probably item id was changed in vanilla SDV. Please xontact the mod author. For harvest quest QF uses the vanilla one.
