### ISSUE TITLE
Possible QF Bug

### ISSUE THREAD

**Issue by whitestarx0312** [purrplingcat/QuestFramework#24]
I'm not sure if QF is causing this bug, but it is my best guess.

As you can see in the image, I keep having my quest menu clogged up by blank entries. This happens to me as a farmhand, but does not happen to the host of my game. Seems to get longer as I complete more quests.

![20210120205406_1](https://user-images.githubusercontent.com/1545854/105621673-ae5ee480-5dcf-11eb-8f5e-078321069947.jpg)

**Comment by whitestarx0312** [comment]
Just in case you need it: https://smapi.io/log/f95862997cf742e5973330dbde00995d

**Comment by purrplingcat** [comment]
Can't reproduce, it works for me.
