### ISSUE TITLE
Quest Framework for Mobile?

### ISSUE THREAD

**Issue by GuardianMilky** [purrplingcat/QuestFramework#30]
I have downloaded Quest Framework starting from version 1.2.1 and it says something like it's outdated and I needed to update it, the problem is that 1.3 won't run on mobile because the DLL couldn't be loaded. I hope to get this for mobile cause this mod is needed for npc adventure(and it's the only err to).

**Comment by purrplingcat** [comment]
There are no QF for mobile, because modern QF requires SDV 1.5 and newest SMAPI and these versions are not for mobile. Also github issues is not forum for asking help, it's source code manager and issue tracker. For next time ask on another places like Discord, SDV forum and etc.
