### ISSUE TITLE
A condition for KnownRecipe and NotKnownRecipe? 

### ISSUE THREAD

**Issue by LenneDalben** [purrplingcat/QuestFramework#4]
Hi PurrplingCat, from the Discord chat, you mentioned it would be possible to implement condition KnownRecipe and NotKnownRecipe

_Originally posted by @LenneDalben in https://github.com/purrplingcat/QuestFramework/issues/3#issuecomment-655882436_

I realized this should be its own issue rather than added to the existing one, since it's different, sorry about that!

**Comment by purrplingcat** [comment]
I'll implement `KnownRecipe` only, because for negative is implemented `not:` prefix in #3 and this prefix will work with `KnownRecipe` too for check not known recipe.

**Comment by purrplingcat** [comment]
I implemented new common global conditions `KnownCraftingRecipe` and `KnownCookingRecipe`

Condition | Example value | Description
--- | --- | ---
KnownCraftingRecipe      | `Furance`                  | Player knows specified crafting recipe.
KnownCookingRecipe       | `Fried Egg`                | Player knows specified cooking recipe.

Also the `not:` prefix for check negative result of these conditions can be applied.
