### ISSUE TITLE
A condition for skill checks?

### ISSUE THREAD

**Issue by LenneDalben** [purrplingcat/QuestFramework#5]
Hi PurrplingCat, me again! Would it be possible to add a condition to check skill levels? For the mod I'm working on, KnownRecipe and NotKnownRecipe will work for what I'm trying to do, but it may be useful for other quest mods to only give the player the quest if they are at a certain farming, fishing, mining, or combat level.
For example, maybe a request for a fish you can't catch until you're a certain level, or something like that.
Like I mentioned, for my mod, the check for recipes will work, this is an idea in case someone else would find it useful :)

**Comment by purrplingcat** [comment]
I'll implement it later in future versions.
