### ISSUE TITLE
Silent Quest + Repeatable Quest for CP

### ISSUE THREAD

**Issue by itsbenter** [purrplingcat/QuestFramework#7]
This is made based on the assumption that silent quest won't show in quest log and won't make any notif. I could be wrong though.

An interesting use case: Unique response for each gift
1. Send item quest type
2. Set it to silent quest
3. Set the dialogue when item is given
3. Make it repeatable
4. Make so that it will always trigger (upon entering farm?)

**Comment by purrplingcat** [comment]
You can do repeatable quests with offers, just setup the conditions in the right way to do in this way.

Silent quests are supported from code, but like the quest will be added without notification and sound, but you can see it in the log without the new tag in the log.

You can do some trigger actions with hooks. Currently are supported two type of hooks: location and tile hook.

**Comment by purrplingcat** [comment]
Btw: for unique responses to each gift it's better make SMAPI mod independent on QF as standalone mod. This usage it's overkill for QF and it's more simple to do it with standalone smapi mod than with QF.

**Comment by itsbenter** [comment]
Ah I just realized that point 4 and 5 basically the same. And yes, it would indeed strange to have tons of active quest at once. I also learn what the silent quest is actually like. Thank you!

**Comment by purrplingcat** [comment]
So I close this issue, because it's not an issue.
